# 一、ndarray
## 1.ndarray特性
### 多维性

In [1]:
import numpy as np
from anaconda_project.prepare import prepare_execute_without_interaction
from astropy.utils.metadata.utils import dtype

In [9]:
arr = np.array(5) # 创建0维ndarray
print(arr)
print('arr的维度:',arr.ndim) # 打印纬度

5
arr的维度: 0


In [10]:
arr = np.array([1,2,3]) # 创建1维ndarray
print(arr)
print('arr的维度:',arr.ndim) # 打印纬度

[1 2 3]
arr的维度: 1


In [14]:
arr = np.array([
    [1,2,3],
    [4,5,6]
]) # 创建2维ndarray
print(arr)
print('arr的维度:',arr.ndim) # 打印纬度

[[1 2 3]
 [4 5 6]]
arr的维度: 2


### 同质性

In [16]:
arr = np.array([1,2,'3']) # 不同的数据类型会被强制转换为相同的数据类型
print(arr)

['1' '2' '3']


In [17]:
arr = np.array([1,2.5]) # 不同的数据类型会被强制转换为相同的数据类型
print(arr)

[1.  2.5]


## 2.ndarray的属性

In [26]:
arr = np.array(1)
print('数组的形状:',arr.shape)
print('数组的维度',arr.ndim)
print('元素的个数',arr.size)
print('元素的数据类型',arr.dtype)

数组的形状: ()
数组的维度 0
元素的个数 1
元素的数据类型 int64


In [28]:
arr = np.array([1,2,'3'])
print('数组的形状:',arr.shape)
print('数组的维度',arr.ndim)
print('元素的个数',arr.size)
print('元素的数据类型',arr.dtype)

数组的形状: (3,)
数组的维度 1
元素的个数 3
元素的数据类型 <U21
转置 ['1' '2' '3']


In [29]:
arr = np.array([[1,2,3],
               [4,5,6]])
print('数组的形状:',arr.shape)
print('数组的维度',arr.ndim)
print('元素的个数',arr.size)
print('转置',arr.T)

数组的形状: (2, 3)
数组的维度 2
元素的个数 6
转置 [[1 4]
 [2 5]
 [3 6]]


## 3.ndarray的创建

In [33]:
# 基础创建
list1 = [4,5,6]
arr = np.array(list1,dtype=np.float64)
print(arr)
print(arr.ndim)

[4. 5. 6.]
1


In [34]:
arr1 = np.copy(arr) # 复制一份
print(arr1)

[4. 5. 6.]


In [36]:
# 预定义形状
# 全0 全1 未初始化 固定值
# 全0
arr = np.zeros((2,3),dtype=np.int64)
print(arr)

[[0 0 0]
 [0 0 0]]


In [66]:
arr = np.zeros((2,),dtype=np.int64)
print(arr)

[0 0]


In [39]:
# 全1
arr = np.ones((2,3),dtype=np.int64)
print(arr)

[[1 1 1]
 [1 1 1]]


In [41]:
# 未初始化
arr = np.empty((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [43]:
# 填其他元素
arr = np.full((3,4),2,dtype=np.int64)
print(arr)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [44]:
arr1 = np.zeros_like(arr) #形状一样 xxx_like
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [48]:
# 等差数列
arr = np.arange(1,10,1) # 步长为1,不包含最后一个值
print(arr)
arr = np.arange(1,10,2)
print(arr)

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [54]:
# 等间隔数列
arr = np.linspace(1,10,10,dtype=int) # 1-10取10份
print(arr)
arr = np.linspace(1,10,3) # 1-10 取3份
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1.   5.5 10. ]


In [222]:
# 指数间隔数列
arr = np.logspace(0,4,2,base=2)
print(arr)
arr = np.logspace(0,4,3,base=2)
print(arr)

[ 1. 16.]
[ 1.  4. 16.]


In [220]:
# 特殊矩阵
# 单位矩阵
arr = np.eye(3,dtype=int)
print(arr)


[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [63]:
# 对角矩阵
arr = np.diag([1,2,3,4,5])
print(arr)
arr = np.diag(np.ones(5,dtype=int))
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [67]:
# 随机数组
# 生成0—1之间的随机浮点数
arr = np.random.rand(2,3)
print(arr)

[[0.31160493 0.61119531 0.05205081]
 [0.83092569 0.01874297 0.12730087]]


In [69]:
# 生成指定范围区间的随机浮点数
arr = np.random.uniform(3,6,size=(2,3))
print(arr)

[[3.52725797 3.6138191  3.29074977]
 [5.73188087 3.27204018 3.41456012]]


In [71]:
# 生成指定范围区间的随机整数
arr = np.random.randint(3,30,size=(2,3))
print(arr)

[[ 4 23  6]
 [27  6 22]]


In [72]:
# 生成正态分布的随机数列
arr = np.random.randn(2,3)
print(arr)

[[-0.67295366 -0.47877707 -1.95679984]
 [ 1.16467705  0.83270651  0.44563291]]


In [73]:
# 设置随机种子
np.random.seed(20)
arr = np.random.randint(1,10,size=(2,3))
print(arr)

[[4 5 7]
 [8 3 1]]


## 4.ndarray的数据类型

bool int float complex(复数)

In [77]:
arr = np.array([1,0,1],dtype='bool')
print(arr)
# arr = np.array([1,1000,1],dtype=np.int8)
# print(arr)

[ True False  True]


## 5.ndarray索引与切片

In [91]:
# 一维数组
arr = np.random.randint(1,100,20)
print(arr)
print(arr[0])
print(arr[:]) # 获取全部数据
print(arr[0:2]) # 获取0-1个元素
print(arr[(arr>10) & (arr<20)]) # 布尔索引
print(arr[slice(2,15,3)]) # slice(start,end,step)


[25 31 65 34  5 94 37 78 28 71 35 98 33  6 94 40 17 37 72 60]
25
[25 31 65 34  5 94 37 78 28 71 35 98 33  6 94 40 17 37 72 60]
[25 31]
[17]
[65 94 28 98 94]


In [104]:
# 二维数组
arr = np.random.randint(1,100,size=(4,8))
print(arr)
print(arr[1,2]) # 单索引
print(arr[:,2]) # 指定列
print(arr[1,:]) # 指定行
print(arr[2,2:5]) # 指定某行/列部分元素
print(arr[arr>50]) # 筛选部分元素
print(arr[1:][arr[1:]>50]) # 筛选指定某行/列部分元素

[[61 80 77 30 52  9 68 89]
 [66 96 49 82  1 32 62 95]
 [48 44 61 43 78 61 82 72]
 [98 28 18 17 86 43 46 92]]
49
[77 49 61 18]
[66 96 49 82  1 32 62 95]
[61 43 78]
[61 80 77 52 68 89 66 96 82 62 95 61 78 61 82 72 98 86 92]
[66 96 82 62 95 61 78 61 82 72 98 86 92]


## 6.ndarray的运算

In [111]:
# 算数运算
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [110]:
# 普通列表
c = [1,2,3]
d = [4,5,6]
print(c+d) # 此处为列表拼接

[1, 2, 3, 4, 5, 6]


In [113]:
# 二维
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[7,8,9],[1,2,3],[4,5,6]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [115]:
# 数组+标量
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a+3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [117]:
# 广播机制
a = np.array([1,2,3]) # 1*3
b = np.array([[9],[3],[4]]) # 3*1
print(a+b)
'''
123    999
123  + 333
123    444

'''

[[10 11 12]
 [ 4  5  6]
 [ 5  6  7]]


In [120]:
# 矩阵运算
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[7,8,9],[1,2,3],[4,5,6]])
print(a*b) # 对应元素相乘
print(a@b) # 矩阵乘

[[ 7 16 27]
 [ 4 10 18]
 [28 40 54]]
[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


# 一、numpy中的常用函数
## 1.基本数学函数

In [126]:
# 计算平方根
print(np.sqrt(9))
print(np.sqrt([1,4,9]))
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [127]:
# 计算指数
print(np.exp(1)) # e的1次方

2.718281828459045


In [128]:
# 计算自然对数 lnx
print(np.log(2.71))

0.9969486348916096


In [136]:
# 三角函数
print(np.sin(np.pi/2))
print(np.sin(np.pi))
print(np.cos(np.pi))

1.0
1.2246467991473532e-16
-1.0


In [137]:
# 绝对值
arr = np.array([-1,-2,3])
print(np.abs(arr))

[1 2 3]
[-1 -1  1]


In [139]:
# 计算a的b次幂
arr = np.array([-1,-2,3])
print(np.power(arr,2))

[1 4 9]


In [141]:
# 四舍五入
print(np.round([1.2,3.7,3.5]))

[1. 4. 4.]


In [142]:
# 向上取整
arr = np.array([1.6,25.1,81.7])
print(np.ceil(arr))

[ 2. 26. 82.]


In [144]:
# 检测缺失值
np.isnan([1,2,np.nan,3])

array([False, False,  True, False])

## 2.统计函数


In [145]:
# 求和、计算平均值、计算中位数、标准差、方差
# 查找最大值、最小值
# 计算分位数、累积和、累积差

In [157]:
arr = np.random.randint(1,20,8)
print(arr)

None


In [154]:
# 求和
print(np.sum(arr))

78


In [155]:
# 计算平均值
print(np.mean(arr))

9.75


In [159]:
# 计算中位数 奇数取中间 偶数取中间两个的平均值
print(np.median([1,4,2]))
print(np.median([1,1,1,1,1,1,1,100]))

2.0
1.0


In [162]:
# 计算标准差和方差
print(np.var([1,2,3])) # 方差 sigma(平均值-x[i])^2 / n
print(np.std([1,2,3])) # 标准差 方差开平方

0.6666666666666666
0.816496580927726


In [166]:
# 计算最值
print(np.max([1,2,4,5]),np.argmax([1,2,4,5])) # arg打印索引
print(np.min([1,2,4,5]),np.argmin([1,2,4,5]))

5 3
1 0


In [175]:
# 分位数
print(np.percentile([1,2,4,5],50))
print(np.percentile([1,2,4,5],25)) # 0.25*3=0.75 1+0.75*(2-1)
print(np.percentile([1,2,4,8],75)) # 0.75*3=2.25 4+(2.25-2)*(5-4)

3.0
1.75
5.0


In [179]:
# 累积和、累积积
arr = np.array([1,2,3])
print(np.sum(arr))
print(np.cumsum(arr)) # 1 1+2 1+2+3
print(np.cumprod(arr)) # 1 1*2 1*2*3

6
[1 3 6]
[1 2 6]


## 3.比较函数
### 比较大小 逻辑运算 检查数组中是否包含true、是否所有都为true、自定义条件

In [183]:
# 大于
print(np.greater([2,3,4,5,6],4))
print(np.greater_equal([2,3,4,5,6],4))
# 小于
print(np.less([2,3,4,5,6],4))
# 等于
print(np.equal([2,3,4,5,6],4))
print(np.equal([2,3,4],[3,4,5]))

[False False False  True  True]
[False False  True  True  True]
[ True  True False False False]
[False False  True False False]
[False False False]


In [186]:
# 逻辑运算
print(np.logical_or([1,0,1],[1,1,1]))
print(np.logical_and([1,0,1],[1,1,1]))
print(np.logical_not([1,0,1]))

[ True  True  True]
[ True False  True]
[False  True False]


In [189]:
# 检查元素是否包含true
print(np.any([0,1,0]))
# 检查元素是否全部true
print(np.all([0,0,0]))

True
False


In [191]:
# 自定义条件 np.where(条件，符合条件，不符合条件)
arr = np.array([1,2,3,4,5])
print(np.where(arr>3,arr,0))
print(np.where(arr>3,1,0))

[0 0 0 4 5]
[0 0 0 1 1]


In [194]:
score = np.random.randint(1,100,20)
print(score)
print(np.where(score>=60,'及格','不及格'))

[30 35 83 43 47 52 22 71 67 19 46 31 32 29 14 87 10 43 83 52]
['不及格' '不及格' '及格' '不及格' '不及格' '不及格' '不及格' '及格' '及格' '不及格' '不及格' '不及格'
 '不及格' '不及格' '不及格' '及格' '不及格' '不及格' '及格' '不及格']


In [195]:
print(np.where(score<60,'不及格',np.where(score<80,'良好','优秀')))

['不及格' '不及格' '优秀' '不及格' '不及格' '不及格' '不及格' '良好' '良好' '不及格' '不及格' '不及格'
 '不及格' '不及格' '不及格' '优秀' '不及格' '不及格' '优秀' '不及格']


In [198]:
# np.select(条件，结果)
print(np.select([score<60,(score>60) & (score<=80),score>80],['不及格','良好','优秀'],default='未知'))

['不及格' '不及格' '优秀' '不及格' '不及格' '不及格' '不及格' '良好' '良好' '不及格' '不及格' '不及格'
 '不及格' '不及格' '不及格' '优秀' '不及格' '不及格' '优秀' '不及格']


In [204]:
# 排序函数
np.random.seed(0)
arr = np.random.randint(1,100,20)
print(arr)
# arr.sort() # 原地排序
# print(arr)
print(np.sort(arr))
print(np.argsort(arr)) # 打印索引

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[ 5 13  7  8 16  0 18  1 14  2 15  3  4 10  6 17  9 11 12 19]


In [206]:
# 去重
print(np.unique(arr))
print(np.unique(arr).size)

[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]
16


In [212]:
# 数组拼接
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.concat((arr1,arr2)))

[1 2 3 4 5 6]


In [214]:
# 数组分割
np.split(arr,4)
np.split(arr,[6,12,18])

[array([45, 48, 65, 68, 68, 10]),
 array([84, 22, 37, 88, 71, 89]),
 array([89, 13, 59, 66, 40, 88]),
 array([47, 89])]

In [218]:
# 调整数组形状
print(np.reshape(arr,(5,4))) # 元素个数要和形状匹配上

[[45 48 65 68]
 [68 10 84 22]
 [37 88 71 89]
 [89 13 59 66]
 [40 88 47 89]]
