# 一、ndarray
## 1、ndarray特性
### 多维性

In [1]:
import numpy as np
from anaconda_project.prepare import prepare_execute_without_interaction

In [9]:
arr = np.array(5) # 创建0维ndarray
print(arr)
print('arr的维度:',arr.ndim) # 打印纬度

5
arr的维度: 0


In [10]:
arr = np.array([1,2,3]) # 创建1维ndarray
print(arr)
print('arr的维度:',arr.ndim) # 打印纬度

[1 2 3]
arr的维度: 1


In [14]:
arr = np.array([
    [1,2,3],
    [4,5,6]
]) # 创建2维ndarray
print(arr)
print('arr的维度:',arr.ndim) # 打印纬度

[[1 2 3]
 [4 5 6]]
arr的维度: 2


### 同质性

In [16]:
arr = np.array([1,2,'3']) # 不同的数据类型会被强制转换为相同的数据类型
print(arr)

['1' '2' '3']


In [17]:
arr = np.array([1,2.5]) # 不同的数据类型会被强制转换为相同的数据类型
print(arr)

[1.  2.5]


## 2.ndarray的属性

In [26]:
arr = np.array(1)
print('数组的形状:',arr.shape)
print('数组的维度',arr.ndim)
print('元素的个数',arr.size)
print('元素的数据类型',arr.dtype)

数组的形状: ()
数组的维度 0
元素的个数 1
元素的数据类型 int64


In [28]:
arr = np.array([1,2,'3'])
print('数组的形状:',arr.shape)
print('数组的维度',arr.ndim)
print('元素的个数',arr.size)
print('元素的数据类型',arr.dtype)

数组的形状: (3,)
数组的维度 1
元素的个数 3
元素的数据类型 <U21
转置 ['1' '2' '3']


In [29]:
arr = np.array([[1,2,3],
               [4,5,6]])
print('数组的形状:',arr.shape)
print('数组的维度',arr.ndim)
print('元素的个数',arr.size)
print('转置',arr.T)

数组的形状: (2, 3)
数组的维度 2
元素的个数 6
转置 [[1 4]
 [2 5]
 [3 6]]


## 3.ndarray的创建

In [33]:
# 基础创建
list1 = [4,5,6]
arr = np.array(list1,dtype=np.float64)
print(arr)
print(arr.ndim)

[4. 5. 6.]
1


In [34]:
arr1 = np.copy(arr) # 复制一份
print(arr1)

[4. 5. 6.]


In [36]:
# 预定义形状
# 全0 全1 未初始化 固定值
# 全0
arr = np.zeros((2,3),dtype=np.int64)
print(arr)

[[0 0 0]
 [0 0 0]]


In [38]:
arr = np.zeros((2,),dtype=np.int64)
print(arr)

[0 0]


In [39]:
# 全1
arr = np.ones((2,3),dtype=np.int64)
print(arr)

[[1 1 1]
 [1 1 1]]


In [41]:
# 未初始化
arr = np.empty((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [43]:
# 填其他元素
arr = np.full((3,4),2,dtype=np.int64)
print(arr)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [44]:
arr1 = np.zeros_like(arr) #形状一样 xxx_like
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
